### ISSUE TITLE
没有模块

### ISSUE THREAD

**Issue by purofle** [I-love-study/graiax-silkcoder#1]
没有_silkv3模块/函数

https://github.com/I-love-study/graiax-silkcoder/blob/5a2bf2b65e90b4e780557c8032a22e0d1a5e4c79/src/graiax/silkcoder/__init__.py#L14

**Comment by I-love-study** [comment]
解决，是我**了忘记把clib塞库里了
升级0.0.5即可解决
如果还不行，请升级setuptools
