### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by ahhhhhhhman** [I-love-study/graiax-silkcoder#10]
[error.txt](https://github.com/I-love-study/graiax-silkcoder/files/7699081/error.txt)
在找了一堆解决办法后依然安装不上
（不会python纯靠教程的萌新）

**Comment by I-love-study** [comment]
你只需要安装python38-dev即刻解决
(可能名字是python-dev, python3-dev)
如： apt install python3-dev ...

**Comment by ahhhhhhhman** [comment]
有点小问题就是。。
我是centOS8

**Comment by I-love-study** [comment]
那就'yum install python38-devel'

**Comment by ahhhhhhhman** [comment]
好了好了安装成功了
万分感谢
