### ISSUE TITLE
SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by TeaPoly** [I-love-study/graiax-silkcoder#11]
It's great to write silk decoder into a python interface. Thanks for your contribution. When I install `graiax-silkcoder` and run example in `README`, then an error has raise: `SyntaxError: 'await' outside function`. 

```python
from graiax import silkcoder

await silkcoder.encode('a.wav', 'a.silk')
```

**Comment by I-love-study** [comment]
Hello
In fact, `encode` and `decode` method in `graiax-silkcoder` is asynchronous.
you can do it by this
```python
import asyncio
from graiax import silkcoder
asycio.run(silkcoder.encode('a.wav', 'a.silk'))
```

or if you want to run in the terminal
just using `python -m asyncio`  to open python

**Comment by TeaPoly** [comment]
> Hello In fact, `encode` and `decode` method in `graiax-silkcoder` is asynchronous. you can do it by this
> 
> ```python
> import asyncio
> from graiax import silkcoder
> asycio.run(silkcoder.encode('a.wav', 'a.silk'))
> ```
> 
> or if you want to run in the terminal just using `python -m asyncio` to open python

Thanks for your reply.
