### ISSUE TITLE
[bugs]输出音频在iOS上无法播放的问题

### ISSUE THREAD

**Issue by I-love-study** [I-love-study/graiax-silkcoder#22]
现阶段的 iOS QQ 对 silk 的 **码率** 要求比较严格
要求必须是小于 25kbps （如 go-cq 就是定为 24kbps）
而现在该库的码率策略是 **尽量将总大小控制在 1Mb 以内**
将考虑给 `encode` `async_encode` 添加 `adaptive_rate: bool = True` 参数
当为 True 则维持上述策略，当为 False 时则将码率默认值改为 24kbps
至于是直接作为一种属性，还是参数，emmmm，你们怎么说

**Comment by synodriver** [comment]
把这些 [参数](https://github.com/synodriver/pysilk/blob/stream/pysilk/_silk.pyx#L85-L94) 加进去

**Comment by I-love-study** [comment]
> 把这些 [参数](https://github.com/synodriver/pysilk/blob/stream/pysilk/_silk.pyx#L85-L94) 加进去

嗯，这些参数我都是直接硬编码进去了（除了码率

**Comment by synodriver** [comment]
> > 把这些 [参数](https://github.com/synodriver/pysilk/blob/stream/pysilk/_silk.pyx#L85-L94) 加进去
> 
> 嗯，这些参数我都是直接硬编码进去了（除了码率

~~太懒了~~（不如换我的，里面能自己设置的参数我全部搞出来了

**Comment by I-love-study** [comment]
> > > 把这些 [参数](https://github.com/synodriver/pysilk/blob/stream/pysilk/_silk.pyx#L85-L94) 加进去
> > 
> > 
> > 嗯，这些参数我都是直接硬编码进去了（除了码率
> 
> ~太懒了~（不如换我的，里面能自己设置的参数我全部搞出来了

没，已经解决了，就是纯摸鱼ing
