### ISSUE TITLE
运行时提示importError：DLL load failed while importing _silkv3：找不到指定的模块。

### ISSUE THREAD

**Issue by gyy0814** [I-love-study/graiax-silkcoder#23]
如题 求助 安装的最新的0.2.5
![image](https://user-images.githubusercontent.com/74656537/170634136-e0df2960-da98-456f-9ade-911a555c1c45.png)
系统是WIN10企业版 21H2
![image](https://user-images.githubusercontent.com/74656537/170634216-2070ceaa-1fdd-4e49-b0ce-2b82f9a4b081.png)
python版本为 3.10.4
![image](https://user-images.githubusercontent.com/74656537/170634294-1c163008-8023-4888-8641-f58d641d7887.png)
使用这个模块的地方是
![image](https://user-images.githubusercontent.com/74656537/170634425-98c8ad4a-ac21-4656-bc2c-9cf3548ebefe.png)
感谢大佬帮助~~~

**Comment by gyy0814** [comment]
附:
群友的windows版本
![)%$PJ6M$0CA)5L6GU6TL{UW](https://user-images.githubusercontent.com/74656537/170637987-347b2570-d580-4547-97d4-bc0454234108.png)
报错信息
![{4J6D)06VP(KUB1`F_ `_8A](https://user-images.githubusercontent.com/74656537/170638060-073aa18f-dc6b-43e2-8e3c-bd5c0075ea08.png)

**Comment by I-love-study** [comment]
请从这里下载安装[C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)
因为 0.2.0 引用了 C++ 标准库中的 `vector`，所以需要下载

**Comment by gyy0814** [comment]
感谢大佬了捏
QwQ
