### ISSUE TITLE
关于c++ build tools的安装

### ISSUE THREAD

**Issue by Emperormummy** [I-love-study/graiax-silkcoder#29]
c++ build tools 里面有超级多组件，可以说明一下具体只用安装哪些就可以了吗

**Comment by I-love-study** [comment]
除了 win_arm64 因为 cibuildtool 的一些问题导致我没编译以外，剩下的支持 python 版本我应该都已经编译好了 win32 跟 win64 版本了，在 x86 跟 x64 中你根本不需要安装 c++ build tools 来编译。
至于需要什么组件
如果你是 win_arm64 的用户，你从 [这里](https://github.com/I-love-study/graiax-silkcoder#%E4%BB%8E-pypi) 的链接点进去下载，安装选项应该就直接有了这一个
<img width="221" alt="image" src="https://user-images.githubusercontent.com/39652142/231160701-34a99b6f-5107-4d69-b9bf-fec4f8e3f6fe.png">
这时候你直接点击安装就行了，没有什么其他需要选择的东西

**Comment by Emperormummy** [comment]
ok
