### ISSUE TITLE
没有 _silkv3 模块

### ISSUE THREAD

**Issue by vivien8261** [I-love-study/graiax-silkcoder#3]
目录下没有，运行会报错
```bash
ImportError: cannot import name '_silkv3' from 'graiax.silkcoder'
```

版本：
graiax-silkcoder 0.0.5
setuptools 54.2.0

**Comment by I-love-study** [comment]
是Windows吗

**Comment by vivien8261** [comment]
Python38，用 0.0.4 版本可以解决，谢谢！但是 wav 转换出来的 silk 失真很严重……可能要研究下参数

**Comment by I-love-study** [comment]
silk本身的最高码率基本上就在70kbps，你听听语音消息也差不多
也有可能是mirai本身的问题(这个问题在mirai已经存在很久了)
你可以尝试一下转成silk再转回来听听
