### ISSUE TITLE
输出音频在Windows QQNT上无法播放

### ISSUE THREAD

**Issue by idanran** [I-love-study/graiax-silkcoder#30]
只有自己能听，别人听不了。

**Comment by RF-Tar-Railt** [comment]
请说明一下如下信息
1. coder版本
2. bot使用的框架（如graia-ariadne）
3. bot的协议端（如mirai2.15+qsign8.9.63)
4. 播放测试环境

**Comment by idanran** [comment]
coder版本：最新
bot使用的框架：Koishi
bot的协议端：betterQQNT的red协议
播放测试环境：Windows 11

**Comment by idanran** [comment]
> > coder版本：最新
> > bot使用的框架：Koishi
> > bot的协议端：betterQQNT的red协议（koishi端使用adapter-red适配器）
> > 播放测试环境：Windows 11
> 
> red啊。。那有可能是适配器的实现问题（比如缺少必需字段）

发送手机QQ录制的音频是可以正常播放的，在别人那里

**Comment by I-love-study** [comment]
能否将音频压制相关代码上传一下，还有“安卓QQ录制的音频”和“压制源音频”

**Comment by idanran** [comment]
> > > > coder版本：最新
> > > > bot使用的框架：Koishi
> > > > bot的协议端：betterQQNT的red协议（koishi端使用adapter-red适配器）
> > > > 播放测试环境：Windows 11
> > > 
> > > red啊。。那有可能是适配器的实现问题（比如缺少必需字段）
> > 
> > 发送手机QQ录制的音频是可以正常播放的，在别人那里
> 
> 我去问问koishi那边（

我觉得安卓QQ语音的码率或者一些奇奇怪怪的参数影响了这个问题

**Comment by idanran** [comment]
> 能否将音频压制相关代码上传一下，还有“安卓QQ录制的音频”和“压制源音频”

稍等

**Comment by idanran** [comment]
> 能否将音频压制相关代码上传一下，还有“安卓QQ录制的音频”和“压制源音频”

已上传，见 https://github.com/idanran/graiax-silkcoder

**Comment by RF-Tar-Railt** [comment]
> > 我去问问koishi那边（
> 
> 我觉得是安卓QQ语音的码率或者一些奇奇怪怪的编码参数影响了这个问题。

怪了，koishi的人说red适配器目前还没做音频发送（

**Comment by idanran** [comment]
> > > 我去问问koishi那边（
> > 
> > 我觉得是安卓QQ语音的码率或者一些奇奇怪怪的编码参数影响了这个问题。
> 
> 怪了，koishi的人说red适配器目前还没做音频发送（

这个是 adapter-red 的
