### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by Mechorca** [I-love-study/graiax-silkcoder#4]
pip安装大佬的库出现了报错...手动下载代码放进项目后也出现了import错误..貌似是找不到_silkv3这个库。请问这是为什么

**Comment by I-love-study** [comment]
这个库是需要编译的，所以直接放进去当然会出错。。。
请问可以把完整的错误贴上来吗

**Comment by I-love-study** [comment]
假设报错有`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

**Comment by I-love-study** [comment]
假设报错的有`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`
假设你是Windows，跟按照以下步骤
1.去[这里](https://visualstudio.microsoft.com/visual-cpp-build-tools/)下载生成工具
2.安装Visual Studio installer
3.在installer里面安装Visual Studio 生成工具 2019里勾选“使用C++的桌面开发”
![image](https://user-images.githubusercontent.com/39652142/126036782-95717932-f1fb-450b-8568-4ef4c70966ea.png)
4.安装完重启电脑，重新pip即可
