### ISSUE TITLE
undefined symbol: SKP_Silk_resampler_private_up2_HQ

### ISSUE THREAD

**Issue by meng-luo** [I-love-study/graiax-silkcoder#7]
python版本：3.9.6
graiax-silkcoder：0.0.16
![Snipaste_2021-08-30_14-35-29](https://user-images.githubusercontent.com/79274361/131317786-6f568ea1-f3f2-4020-a43f-596be378aa69.png)

**Comment by I-love-study** [comment]
虽然还判断不了具体原因（手上没有armv7l的设备）
但是你先试试重装怎么样
或者你可以尝试一下去编译一下[silkv3](https://github.com/kn007/silk-v3-decoder)
假设在编译完后也出现了这个问题
那我就不知道怎么修了（本人并不会C语言）

**Comment by I-love-study** [comment]
刚刚从某个库里面找到了[SILK_SDK_SRC_FIX_v1.0.9](https://github.com/ploverlake/silk/tree/master/src/SILK_SDK_SRC_FIX_v1.0.9)
经检验，这个可以在armv6l环境中编译成功，应该是解决了该issue
假设有问题再开
